#! /usr/bin/env python
# -*- encoding: utf-8 -*-

import argparse

def scoreboard(args):
    print('score')

def test(args):
    print('test')

def main():
    commands = {
        'scoreboard': scoreboard,
        'score': scoreboard,
        'test': test,
    }

    parser = argparse.ArgumentParser(description='nizk CTF cli')
    parser.add_argument('command', metavar='<command>', nargs=1,
        help='command', choices=commands.keys())
    args = parser.parse_args()

    commands[args.command[0]](args)

if __name__ == '__main__':
    main()
